FROM eclipse-temurin:26-jre-alpine
WORKDIR /app
COPY build/quarkus-app/lib/      /app/lib/
COPY build/quarkus-app/*.jar     /app/
COPY build/quarkus-app/app/      /app/app/
COPY build/quarkus-app/quarkus/  /app/quarkus/
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/quarkus-run.jar"]
