quarkus.http.port=8080
quarkus.http.root-path=/

quarkus.redis.hosts=redis://${FT_REDIS_HOST:localhost}:6379
quarkus.redis.timeout=3s

quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${FT_DB_USER}
%prod.quarkus.datasource.password=${FT_DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${FT_DB_URL}
%prod.quarkus.hibernate-orm.schema-management.strategy=none

%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=dev-import.sql

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=test-import.sql
%test.quarkus.redis.devservices.enabled=true

quarkus.hibernate-orm.log.sql=false